### PR TITLE
use tempdir for package cache in batch mode, prompt otherwise, per Revolution request

### PR DESCRIPTION
**Pull request by piccolbo**
in response to CRAN constraints

### CODE REVIEW

**Comment by andrie** [comment]
Hi, @piccolbo 

Thank you for making this change.  Some observations:

1. It seems unnecesarily harsh to always create the `.checkpoint` in `tempdir()` when in batch mode. My interpretation of your code is that even if the user specifies an alternative folder, and if this folder doesn't exist, then we create in `tempdir()`.

2. I don't believe this is necessary. We can run all the unit test by specifying `tempdir()` as the destination folder for checkpoint. This satisfies CRAN, because we don't need any permission to create new folders in `tempdir()`.

3. So an alternative interpretation is to `stop()` if the `.checkpoint` folder doesn't exist AND the user didn't change the default. If the user changed the destination folder, even if it's a subfolder of `/home`, then I propose we accept this as permission granted.

**Comment by piccolbo** [comment]
Yes, the intention was only to create in tmpdir if one doesn't find the default. That's already stretching the policy in that we are using previous user consent to write again to disk, but I think it follows the spirit if  not the letter. Let me check that again.

**Comment by piccolbo** [comment]
I think you are proposing to change CRAN policy. I am all for it, but that's not what I was told to implement.

**Comment by piccolbo** [comment]
Yes line 30 checkpointPaths.R if directory exists, return without further ado. No questions, no creation no nothing. Just use.

**Comment by piccolbo** [comment]
As far as alternative interpretations, they are great but I had marching orders from DC and I even sent him a code sketch and there was no mention of stops or what not. I think you need to escalate if you want to reopen the specs. We need to comply with both policy  and  running R CMD checks with no leftovers, so as far as taking XYZ as user consent, you've got to talk to UL or other core member and see if they go with your interpretation.

**Comment by revodavid** [comment]
Small issue: on Mac, the message prompt has a doubled slash:
```
Can I create directory ~//.checkpoint for internal checkpoint use?
```

**Comment by piccolbo** [comment]
Done but I don't know if anyone noticed, there's a `dir.create` call in the vignette which creates yet again `~/.checkpoint`. Assuming that will irk BR as well I am trying to fix it.

**Comment by piccolbo** [comment]
OK, so if the vignette cleans up after itself, the tests fail. Back to square one.

**Comment by piccolbo** [comment]
Abandoned. See next pull request

**Pull request closed without merging**
